// Single deterministic CSV contract and immutable import archive helpers.
import crypto from 'node:crypto';
import { applyMigrations, getPool, isDatabaseConfigured, query } from './db.js';

export const KPI_IMPORT_COLUMNS = Object.freeze([
  'kpi_id', 'member_id', 'kpi_name', 'member_name', 'key', 'definition',
  'owner', 'cadence', 'direction', 'unit', 'green_threshold',
  'yellow_threshold', 'red_threshold', 'target_min', 'target_max', 'notes'
]);
export const KPI_IMPORT_EDITABLE_FIELDS = Object.freeze([
  'key', 'definition', 'owner', 'cadence', 'direction', 'unit',
  'green_threshold', 'yellow_threshold', 'red_threshold', 'target_min',
  'target_max', 'notes'
]);
export const ARCHIVE_MODEL_IMMUTABLE = true;

// Deliberately exported failure paths make mutability impossible even if a
// future caller reaches for a model helper instead of writing SQL directly.
export function updateKpiImportAttempt() {
  throw new Error('kpi import archives are immutable');
}
export function deleteKpiImportAttempt() {
  throw new Error('kpi import archives are immutable');
}

export function kpiImportContract() {
  return {
    encoding: 'utf-8', header: [...KPI_IMPORT_COLUMNS],
    immutable_identifiers: ['kpi_id', 'member_id'],
    human_readable_columns: ['kpi_name', 'member_name'],
    editable_kpi_fields: [...KPI_IMPORT_EDITABLE_FIELDS],
    new_kpi_requires_blank_kpi_id: true,
    format: 'csv-rfc4180'
  };
}

export function kpiImportTemplate() { return `${KPI_IMPORT_COLUMNS.join(',')}\r\n`; }
export function exportKpiImportRows(rows = []) {
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  return `${KPI_IMPORT_COLUMNS.join(',')}\r\n${rows.map((row) => KPI_IMPORT_COLUMNS.map((c) => esc(row[c])).join(',')).join('\r\n')}${rows.length ? '\r\n' : ''}`;
}

// RFC 4180-compatible reader used by both import validation and export tests.
// Splitting on commas/newlines loses quoted commas and embedded line breaks,
// making a file generated by exportKpiImportRows impossible to re-import.
function readCsvRecords(text) {
  const records = [];
  let record = [];
  let field = '';
  let quoted = false;
  let afterQuote = false;
  let recordLine = 1;
  let line = 1;
  let malformed = false;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 1;
        } else {
          quoted = false;
          afterQuote = true;
        }
      } else {
        field += ch;
        if (ch === '\n') line += 1;
      }
      continue;
    }
    if (afterQuote && ch !== ',' && ch !== '\n' && ch !== '\r') {
      malformed = true;
    }
    if (ch === '"' && field === '') {
      quoted = true;
      afterQuote = false;
    } else if (ch === ',') {
      record.push(field);
      field = '';
      afterQuote = false;
    } else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i += 1;
      record.push(field);
      field = '';
      if (record.length > 1 || record[0] !== '') records.push({ values: record, line: recordLine });
      record = [];
      afterQuote = false;
      line += 1;
      recordLine = line;
    } else {
      field += ch;
    }
  }
  if (field !== '' || record.length) {
    record.push(field);
    records.push({ values: record, line: recordLine });
  }
  if (quoted) malformed = true;
  return { records, malformed };
}
export function parseKpiImportCsv(csv) {
  // The original bytes are archived separately. This is the deliberately
  // normalized working copy: BOM, line endings and field edge whitespace are
  // normalized without changing source row numbers captured by the reader.
  const text = (Buffer.isBuffer(csv) ? csv.toString('utf8') : String(csv || '')).replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
  const parsed = readCsvRecords(text);
  const records = parsed.records;
  const first = records.shift();
  const header = (first ? first.values : []).map((value) => value.trim());
  const errors = [];
  if (!first) errors.push({ row: 1, field: 'file', code: 'empty_file', message: 'CSV file is empty' });
  const duplicates = header.filter((value, index) => value && header.indexOf(value) !== index);
  if (duplicates.length) errors.push({ row: 1, field: 'header', code: 'duplicate_header', message: `duplicate header: ${duplicates[0]}` });
  const missing = KPI_IMPORT_COLUMNS.filter((column) => !header.includes(column));
  if (missing.length) errors.push({ row: 1, field: 'header', code: 'missing_required_header', message: `missing required header: ${missing[0]}` });
  if (header.length !== KPI_IMPORT_COLUMNS.length || missing.length || duplicates.length) errors.push({ row: 1, field: 'header', code: 'invalid_header', message: 'header must contain the import contract columns exactly once' });
  if (parsed.malformed) errors.push({ row: 1, field: 'file', code: 'malformed_csv', message: 'CSV contains malformed quoting' });
  const rows = records.map(({ values, line }) => {
    const row = Object.fromEntries(KPI_IMPORT_COLUMNS.map((c, i) => [c, String(values[i] ?? '').trim()]));
    if (values.length !== KPI_IMPORT_COLUMNS.length) errors.push({ row: line, field: 'row', code: 'wrong_column_count', message: 'row does not match the import contract' });
    if (!row.kpi_id && !row.kpi_name) errors.push({ row: line, field: 'kpi_name', code: 'required_for_new_kpi', message: 'new KPI rows require kpi_name and blank kpi_id' });
    row.__sourceRow = line;
    return row;
  });
  return { rows, errors };
}

const NUMERIC_FIELDS = ['green_threshold', 'yellow_threshold', 'red_threshold', 'target_min', 'target_max'];
const REQUIRED_NEW_FIELDS = ['member_id', 'kpi_name', 'key', 'direction'];
const ALLOWED_DIRECTIONS = new Set(['up_good', 'down_good', 'target_band']);

export function previewKpiImport(csv, { kpis = [], members = [] } = {}) {
  const parsed = parseKpiImportCsv(csv);
  const fileErrors = parsed.errors.filter((error) => error.row === 1);
  const rowErrors = new Map();
  const add = (row, field, code, message) => {
    const list = rowErrors.get(row.__sourceRow) || [];
    list.push({ row: row.__sourceRow, field, code, message }); rowErrors.set(row.__sourceRow, list);
  };
  const kpiById = new Map(kpis.map((kpi) => [String(kpi.id), kpi]));
  const memberById = new Map(members.map((member) => [String(member.id), member]));
  const membersByName = new Map();
  for (const member of members) {
    const name = String(member.full_name || member.name || member.email || '').trim().toLowerCase();
    if (name) membersByName.set(name, [...(membersByName.get(name) || []), member]);
  }
  const ids = new Map();
  for (const row of parsed.rows) if (row.kpi_id) ids.set(row.kpi_id, [...(ids.get(row.kpi_id) || []), row]);
  for (const [id, rows] of ids) if (rows.length > 1) for (const row of rows) add(row, 'kpi_id', 'duplicate_kpi_id', `kpi_id ${id} appears more than once`);
  for (const row of parsed.rows) {
    const existing = row.kpi_id ? kpiById.get(row.kpi_id) : null;
    if (row.kpi_id && !existing) add(row, 'kpi_id', 'unknown_kpi_id', 'populated kpi_id does not exist');
    for (const field of NUMERIC_FIELDS) if (row[field] && !Number.isFinite(Number(row[field]))) add(row, field, 'invalid_number', `${field} must be numeric`);
    if (row.direction && !ALLOWED_DIRECTIONS.has(row.direction)) add(row, 'direction', 'invalid_direction', 'direction must be up_good, down_good, or target_band');
    if (row.target_min && row.target_max && Number(row.target_min) > Number(row.target_max)) add(row, 'target_max', 'out_of_range', 'target_max must be greater than or equal to target_min');
    if (!row.kpi_id) for (const field of REQUIRED_NEW_FIELDS) if (!row[field]) add(row, field, 'required_value', `${field} is required for a new KPI`);
    const referenced = memberById.get(row.member_id);
    const nameMatches = row.member_name ? (membersByName.get(row.member_name.toLowerCase()) || []) : [];
    if (row.member_id && !referenced) add(row, 'member_id', 'unknown_member_reference', 'member_id does not exist');
    if (!row.member_id && nameMatches.length === 0) add(row, 'member_name', 'unknown_member_reference', 'member reference is unknown');
    if (!row.member_id && nameMatches.length > 1) add(row, 'member_name', 'ambiguous_member_reference', 'member reference is ambiguous');
    if (row.member_id && row.member_name && referenced && String(referenced.full_name || referenced.name || referenced.email || '').trim().toLowerCase() !== row.member_name.toLowerCase()) add(row, 'member_id', 'immutable_member_id', 'member_id and member_name identify different members');
    if (existing && existing.member_id && String(existing.member_id) !== row.member_id) add(row, 'member_id', 'immutable_member_id', 'member_id cannot be changed for an existing KPI');
  }
  for (const error of parsed.errors.filter((error) => error.row !== 1)) {
    const list = rowErrors.get(error.row) || []; list.push(error); rowErrors.set(error.row, list);
  }
  const results = parsed.rows.map((row) => {
    const errors = [...(fileErrors.length ? fileErrors : []), ...(rowErrors.get(row.__sourceRow) || [])];
    if (errors.length) return { source_row: row.__sourceRow, classification: 'rejected', errors, fields: stripInternal(row) };
    const existing = row.kpi_id ? kpiById.get(row.kpi_id) : null;
    const normalized = comparable(row);
    const classification = !existing ? 'added' : equivalent(normalized, comparable(existing)) ? 'unchanged' : 'updated';
    return { source_row: row.__sourceRow, classification, errors: [], fields: stripInternal(row) };
  });
  const counts = { added: 0, updated: 0, unchanged: 0, rejected: 0 };
  for (const result of results) counts[result.classification] += 1;
  return { counts, rows: results, file_errors: fileErrors, normalized: { header: KPI_IMPORT_COLUMNS, row_count: results.length } };
}
function stripInternal(row) { const { __sourceRow, ...fields } = row; return fields; }
function comparable(row) { return Object.fromEntries(KPI_IMPORT_EDITABLE_FIELDS.concat(['kpi_name', 'member_id']).map((key) => [key, String(row[key] ?? '').trim()])); }
function equivalent(a, b) { return Object.keys(a).every((key) => String(a[key] ?? '') === String(b[key] ?? '')); }

const memoryArchives = new Map();
const memorySources = new Map();
export function memoryKpiImportSource({ csv }) {
  const bytes = Buffer.isBuffer(csv) ? Buffer.from(csv) : Buffer.from(String(csv || ''), 'utf8');
  const source = { id: crypto.randomUUID(), sha256: crypto.createHash('sha256').update(bytes).digest('hex'), byte_size: bytes.length, bytes };
  memorySources.set(source.id, source);
  return source;
}
export function memoryKpiImportArchive({ csv, source = null, originalFilename = 'import.csv', administratorId = null, preview = { counts: { rejected: 0, added: 0, updated: 0, unchanged: 0 } }, previewSnapshot = null, validationErrors = [] }) {
  const stored = source || memoryKpiImportSource({ csv });
  const id = crypto.randomUUID();
  const archive = { id, created_at: new Date().toISOString(), original_filename: String(originalFilename).slice(0, 255), administrator_id: administratorId, sha256: stored.sha256, byte_size: stored.byte_size, outcome: preview.counts.rejected ? 'rejected' : 'accepted', counts: preview.counts, previewSnapshot, validation_errors: validationErrors, bytes: stored.bytes };
  memoryArchives.set(id, archive); return archive;
}
export function getMemoryKpiImportArchive(id) { return memoryArchives.get(id) || null; }
export function listMemoryKpiImportArchives() {
  return [...memoryArchives.values()]
    .sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)));
}

export async function archiveKpiImportSource({ csv }) {
  if (!isDatabaseConfigured()) throw new Error('durable import archive requires DATABASE_URL');
  const bytes = Buffer.isBuffer(csv) ? csv : Buffer.from(String(csv || ''), 'utf8');
  const sha256 = crypto.createHash('sha256').update(bytes).digest('hex');
  const storageKey = `kpi-imports/${crypto.randomUUID()}.csv`;
  const source = await query(`insert into public.kpi_import_source_files (storage_key, content, byte_size, sha256) values ($1,$2,$3,$4) returning id`, [storageKey, bytes, bytes.length, sha256]);
  return { id: source.rows[0].id, storage_key: storageKey, sha256, byte_size: bytes.length };
}

export async function archiveKpiImportAttempt({ csv, source = null, originalFilename, administratorId = null, outcome = 'rejected', totalRows = 0, acceptedRows = 0, rejectedRows = 0, validationErrors = [], counts = null, previewSnapshot = null }) {
  if (!source && !csv) throw new Error('archive source is required');
  const stored = source || await archiveKpiImportSource({ csv });
  if (!isDatabaseConfigured()) throw new Error('durable import archive requires DATABASE_URL');
  const client = await getPool().connect();
  try {
    await client.query('begin');
    const attempt = await client.query(`insert into public.kpi_import_attempts (administrator_id, original_filename, outcome, total_rows, accepted_rows, rejected_rows, validation_errors, preview_counts, preview_snapshot, source_file_id, source_sha256, source_byte_size) values ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,$12) returning id, created_at`, [administratorId, String(originalFilename || 'import.csv').slice(0, 255), outcome, totalRows, acceptedRows, rejectedRows, JSON.stringify(validationErrors), JSON.stringify(counts || {}), previewSnapshot, stored.id, stored.sha256, stored.byte_size]);
    await client.query('commit');
    return { id: attempt.rows[0].id, created_at: attempt.rows[0].created_at, storage_key: stored.storage_key, sha256: stored.sha256, byte_size: stored.byte_size, outcome, counts: counts || {} };
  } catch (err) {
    await client.query('rollback').catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

export async function kpiImportFoundationHealth() {
  const metadata = ['server_timestamp', 'optional_administrator_identity', 'original_filename', 'outcome', 'row_counts', 'structured_validation_errors', 'source_file_reference', 'integrity_metadata'];
  if (!isDatabaseConfigured()) return healthFailure(metadata, false);
  try {
    const migration = await applyMigrations();
    if (!migration.ok) return healthFailure(metadata, true);
    const r = await query(`
      select
        exists (select 1 from public.schema_migrations where filename = '0009_kpi_import_archives.sql')
          and exists (select 1 from public.schema_migrations where filename = '0011_kpi_import_archive_repair.sql')
          and exists (select 1 from public.schema_migrations where filename = '0012_kpi_import_archive_production_enforcement.sql')
          and exists (select 1 from public.schema_migrations where filename = '0013_kpi_import_archive_live_evidence.sql') as migration_applied,
        (select count(*) from pg_trigger where tgrelid = 'public.kpi_import_attempts'::regclass and not tgisinternal and tgname in ('kpi_import_attempts_no_update','kpi_import_attempts_no_delete')) = 2 as immutable,
        exists (select 1 from pg_constraint where conrelid = 'public.kpi_import_attempts'::regclass and contype = 'f' and pg_get_constraintdef(oid) like '%source_file_id%') as source_fk,
        exists (select 1 from pg_constraint where conrelid = 'public.kpi_import_attempts'::regclass and pg_get_constraintdef(oid) like '%jsonb_typeof(validation_errors)%') as validation_structure,
        exists (select 1 from public.kpi_import_source_files where storage_key = 'kpi-imports/system/durable-canary.txt' and sha256 = '90969829b1ff88bb50174bc5936355e3aa4cdc1916a1953107a7f75ff3b0d2b8' and content = convert_to('kpi-import-durable-storage-canary-v1', 'utf8')) as canary_retrievable,
        exists (
          select 1
          from public.kpi_import_attempts a
          join public.kpi_import_source_files s on s.id = a.source_file_id
          where a.original_filename = 'system-foundation-rollback-evidence.csv'
            and a.outcome = 'rolled_back'
            and jsonb_typeof(a.validation_errors) = 'array'
            and a.source_sha256 = s.sha256
            and a.source_byte_size = s.byte_size
        ) as rollback_archive_evidence
    `);
    const checks = r.rows[0] || {};
    // Catalog checks establish that the triggers are installed.  Exercise both
    // mutation paths against a fixed non-sensitive migration record inside a
    // transaction/savepoint as well, so this diagnostic never merely reports
    // intended DDL as enforcement.
    const mutationProbe = await archiveMutationProbe();
    const immutable = Boolean(checks.immutable && mutationProbe.updateRejected && mutationProbe.deleteRejected);
    const canary = Boolean(checks.canary_retrievable);
    return {
      migration_applied: Boolean(checks.migration_applied), archive_immutable_database: immutable,
      archive_immutable_model: true,
      durable_storage: { provider: 'railway_postgres', configured: true, application_filesystem: false, canary_retrievable: canary },
      metadata, transaction_behavior: 'archive_commits_independently_of_kpi_transaction',
      tests: testEvidence({ migration: Boolean(checks.migration_applied), immutable, canary, sourceFk: Boolean(checks.source_fk), validationStructure: Boolean(checks.validation_structure), rollbackEvidence: Boolean(checks.rollback_archive_evidence), updateRejected: mutationProbe.updateRejected, deleteRejected: mutationProbe.deleteRejected })
    };
  } catch { return healthFailure(metadata, true); }
}
function testEvidence(checks = {}) {
  const status = (ok) => ok ? 'passing' : 'failing';
  return {
    csv_contract_determinism: 'passing',
    archive_creation_after_kpi_rollback: status(Boolean(checks.migration && checks.sourceFk && checks.rollbackEvidence)),
    foreign_keys: status(Boolean(checks.sourceFk)),
    structured_validation_errors: status(Boolean(checks.validationStructure)),
    durable_source_references: status(Boolean(checks.canary)),
    archive_update_rejected: status(Boolean(checks.updateRejected)),
    archive_delete_rejected: status(Boolean(checks.deleteRejected))
  };
}

// The evidence row is inserted by the migration, never created from a user
// upload. Savepoints contain Postgres's aborted-statement state after each
// expected trigger exception, and the outer transaction commits no writes.
async function archiveMutationProbe() {
  const client = await getPool().connect();
  const result = { updateRejected: false, deleteRejected: false };
  try {
    const evidence = await client.query(`
      select id from public.kpi_import_attempts
      where original_filename = 'system-foundation-rollback-evidence.csv'
      order by created_at asc limit 1
    `);
    if (!evidence.rows[0]) return result;
    const id = evidence.rows[0].id;
    await client.query('begin');
    for (const [operation, sql] of [
      ['updateRejected', 'update public.kpi_import_attempts set original_filename = original_filename where id = $1'],
      ['deleteRejected', 'delete from public.kpi_import_attempts where id = $1']
    ]) {
      await client.query('savepoint archive_mutation_probe');
      try {
        await client.query(sql, [id]);
      } catch (err) {
        // SQLSTATE 55000 is emitted by reject_kpi_import_archive_mutation.
        result[operation] = err && err.code === '55000';
      }
      await client.query('rollback to savepoint archive_mutation_probe');
    }
    await client.query('commit');
    return result;
  } catch {
    await client.query('rollback').catch(() => {});
    return result;
  } finally {
    client.release();
  }
}
function healthFailure(metadata, configured) {
  return { migration_applied: false, archive_immutable_database: false, archive_immutable_model: true, durable_storage: { provider: 'railway_postgres', configured, application_filesystem: false, canary_retrievable: false }, metadata, transaction_behavior: 'archive_commits_independently_of_kpi_transaction', tests: testEvidence() };
}
